version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node version:"
      - node -v
      - npm -v
      - npm install

  pre_build:
    commands:
      - echo "Repo      : $REPO_NAME"
      - echo "Branch    : $BRANCH_NAME"
      - echo "Commit ID : $COMMIT_ID"
      - echo "Deploying to bucket: $S3_BUCKET"

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Deploying React build to S3"
      - aws s3 sync dist/ s3://$S3_BUCKET --delete
